{
 "title": "Cache-Insider",
 "time": { "from": "2025-12-29T13:35:16.227Z", "to": "2025-12-29T13:50:58.088Z" },
 "panels": [
  {
   "title": "API Gateway – P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(api_gateway_request_latency_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_hits_total)\r\n/\r\n(sum(cache_hits_total) + sum(cache_misses_total))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Gateway – P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(api_gateway_request_latency_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Evictions (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(cache_evictions_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Gateway – Request Rate by Method",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(api_gateway_requests_total[1m])) by (method)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(cache_misses_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Instance Cache Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "rate(cache_hits_total[1m]) + rate(cache_misses_total[1m])\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Gateway – Request Rate (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(api_gateway_requests_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}